title: Algorismi.nl
description: Algorismi website
theme: jekyll-theme-architect
google_analytics: [G-EL2T5RENF6]
url: 'https://algorismi.nl'
github_username: incyi
github: [metadata]
show_downloads: false
plugins:
  - jekyll-sitemap
